### ISSUE TITLE
CLIPTextHead missing 1 required positional argument: 'arch'

### ISSUE THREAD

**Issue by langyijun** [Yunkun-Zhang/CITE#3]
In the file "zeroshot_clip-vitb16_bs128_i1000.py", no arch parameter has been passed to the "head" in the code"head=dict(type='CLIPTextHead', texts=[prompt.format(t) for t in TEXTS]))". 
![image](https://github.com/Yunkun-Zhang/CITE/assets/37616133/4e190900-c5b8-40b6-b337-08d2dd24d98b)
But the class CLIPTextHead requires a parameter "arch" in the init funciton
![image](https://github.com/Yunkun-Zhang/CITE/assets/37616133/b5b16288-ed6a-4423-b203-5b0d058e3e00)
which cause TypeError

**Comment by Yunkun-Zhang** [comment]
Thanks for mentioning this mistake! Add "arch=arch" to the "head" config and it should be working. The code has been modified.

**Comment by langyijun** [comment]
Thanks for replay！I have tried to solve the error by adding the parameter, but raising new runtimeError."`RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.`"
The same model has been pass to the backbone and the head twice in line 17 and 18.
It does not work `here```

**Comment by Yunkun-Zhang** [comment]
Thanks for pointing that out. This is caused by `self.logit_scale = model.logit_scale.exp()` in line 136 of `models/clip_models.py`. You may change the line to `self.logit_scale = model.logit_scale.exp().item()` so that the model is not passed twice.

What's more, note that the zero-shot setting is for testing without training (seems the file name is misleading). Training with this config will update no model parameters unless you add `fix=False` to `CLIPImageBackbone`.

**Comment by langyijun** [comment]
thanks it works!zero-shot setting is for testing!
